"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { Banknote, Landmark, Plus, ReceiptText, RefreshCw, WalletCards } from "lucide-react";

type Dashboard = { accounts: any[]; plans: any[]; reservations: any[]; entries: any[] };
const money = (value: number, currency: string) => new Intl.NumberFormat("tr-TR", { style: "currency", currency }).format(value);
const date = (value: string | Date) => new Intl.DateTimeFormat("tr-TR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value));

async function json(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json" }, cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "İşlem tamamlanamadı."); return data; }

export function AccountingDashboard() {
  const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { setData(await json("/api/accounting")); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Veriler yüklenemedi."); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function submit(event: FormEvent<HTMLFormElement>, success: string) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); const form = event.currentTarget; const raw = Object.fromEntries(new FormData(form)); const payload: any = { ...raw }; for (const key of ["openingBalance", "totalAmount", "installmentCount", "amount"]) if (key in payload) payload[key] = Number(payload[key]); if (payload.occurredAt) payload.occurredAt = new Date(payload.occurredAt).toISOString(); try { await json("/api/accounting", { method: "POST", body: JSON.stringify(payload) }); form.reset(); await load(); setNotice(success); } catch (e) { setError(e instanceof Error ? e.message : "İşlem tamamlanamadı."); } finally { setBusy(false); } }
  const totals: Record<string, number> = (data?.accounts || []).reduce((map: Record<string, number>, account) => ({ ...map, [account.currency]: (map[account.currency] || 0) + account.balance }), {});
  const overdue = (data?.plans || []).flatMap((plan) => plan.installments.map((item: any) => ({ ...item, plan }))).filter((item) => item.paid < item.amount && new Date(item.dueDate) < new Date()).length;
  return <main className="page-shell space-y-7">
    <header className="admin-page-header"><div className="admin-page-header__title"><span className="admin-eyebrow">Finans operasyonu</span><h1>Muhasebe ve kasa</h1><p>Kasa ve banka bakiyelerini, rezervasyon borçlarını, taksit vadelerini ve manuel tahsilatları yönetin.</p></div><div className="admin-page-actions"><button className="btn" onClick={() => void load()}><RefreshCw size={16}/>Yenile</button></div></header>
    {error && <p className="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800" role="alert">{error}</p>}{notice && <p className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800" role="status">{notice}</p>}
    <section className="admin-kpi-grid">{Object.entries(totals).map(([currency, value]) => <article className="admin-kpi" key={currency}><div className="admin-kpi__top"><span>Toplam bakiye · {currency}</span><span className="admin-kpi__icon"><Banknote size={18}/></span></div><strong>{money(value, currency)}</strong><small>Aktif kasa ve banka hesapları</small></article>)}<article className="admin-kpi"><div className="admin-kpi__top"><span>Açık ödeme planı</span><span className="admin-kpi__icon"><ReceiptText size={18}/></span></div><strong>{data?.plans.filter((p) => p.remaining > 0).length || 0}</strong><small>{overdue} geciken taksit</small></article></section>
    <div className="admin-dashboard-grid"><section className="panel p-5"><div className="admin-section-heading"><div><h2>Kasa ve banka hesapları</h2><p>Bakiyeler para birimine göre ayrı tutulur</p></div><Landmark size={20}/></div><div className="admin-list">{data?.accounts.map((account) => <div className="admin-list-item" key={account.id}><div><h3>{account.name}</h3><p>{account.type === "CASH" ? "Nakit kasa" : "Banka hesabı"} · {account.currency}</p></div><strong>{money(account.balance, account.currency)}</strong></div>)}</div><form className="mt-4 grid gap-3 md:grid-cols-4" onSubmit={(e) => void submit(e, "Hesap oluşturuldu.")}><input type="hidden" name="action" value="account"/><input className="input" name="name" required placeholder="Hesap adı"/><select className="input" name="type"><option value="CASH">Nakit</option><option value="BANK">Banka</option></select><select className="input" name="currency"><option>TRY</option><option>EUR</option><option>USD</option><option>GBP</option></select><input className="input" name="openingBalance" type="number" step="0.01" defaultValue="0"/><button className="btn-primary md:col-span-4" disabled={busy}><Plus size={16}/>Hesap ekle</button></form></section>
    <section className="panel p-5"><div className="admin-section-heading"><div><h2>Ödeme planı oluştur</h2><p>Rezervasyon borcunu eşit taksitlere bölün</p></div><WalletCards size={20}/></div><form className="space-y-3" onSubmit={(e) => void submit(e, "Ödeme planı oluşturuldu.")}><input type="hidden" name="action" value="plan"/><select className="input" name="reservationId" required><option value="">Rezervasyon seçin</option>{data?.reservations.map((r) => <option value={r.id} key={r.id}>{r.code} · {r.contactName} · {r.departure.tour.name}</option>)}</select><div className="grid grid-cols-2 gap-3"><input className="input" name="totalAmount" type="number" min="0.01" step="0.01" required placeholder="Toplam tutar"/><select className="input" name="currency"><option>TRY</option><option>EUR</option><option>USD</option><option>GBP</option></select><input className="input" name="installmentCount" type="number" min="1" max="24" defaultValue="1" required/><input className="input" name="firstDueDate" type="date" required/></div><button className="btn-primary w-full" disabled={busy}>Planı oluştur</button></form></section></div>
    <section className="panel p-5"><div className="admin-section-heading"><div><h2>Tahsilat ve gider kaydı</h2><p>Kasa hareketi oluşturun; tahsilatı ödeme planı ve taksitle eşleştirin</p></div></div><form className="grid gap-3 md:grid-cols-3" onSubmit={(e) => void submit(e, "Kasa hareketi kaydedildi.")}><input type="hidden" name="action" value="entry"/><select className="input" name="accountId" required><option value="">Kasa/Banka seçin</option>{data?.accounts.map((a) => <option value={a.id} key={a.id}>{a.name} · {a.currency}</option>)}</select><select className="input" name="direction"><option value="INCOME">Gelir / Tahsilat</option><option value="EXPENSE">Gider / İade</option></select><select className="input" name="type"><option value="RESERVATION_PAYMENT">Rezervasyon tahsilatı</option><option value="EXPENSE">Gider</option><option value="REFUND">İade</option><option value="ADJUSTMENT">Düzeltme</option></select><select className="input" name="financeId"><option value="">Ödeme planı yok</option>{data?.plans.filter((p) => p.remaining > 0).map((p) => <option value={p.id} key={p.id}>{p.reservation.code} · {p.reservation.contactName} · kalan {money(p.remaining,p.currency)}</option>)}</select><select className="input" name="installmentId"><option value="">Taksit seçilmedi</option>{data?.plans.flatMap((p) => p.installments.filter((i:any) => i.paid < i.amount).map((i:any) => <option value={i.id} key={i.id}>{p.reservation.code} · {i.sequence}. taksit · {date(i.dueDate)} · {money(i.amount-i.paid,p.currency)}</option>))}</select><input className="input" name="amount" type="number" min="0.01" step="0.01" required placeholder="Tutar"/><input className="input" name="occurredAt" type="datetime-local" required/><input className="input md:col-span-2" name="description" required placeholder="Açıklama"/><input className="input" name="reference" placeholder="Dekont / referans"/><button className="btn-primary md:col-span-3" disabled={busy}>Hareketi kaydet</button></form></section>
    <section className="panel p-5"><div className="admin-section-heading"><div><h2>Ödeme planları</h2><p>Ödenen, kalan ve vade durumu</p></div></div><div className="admin-list">{data?.plans.map((plan) => <article className="admin-list-item" key={plan.id}><div className="admin-list-item__main"><h3>{plan.reservation.code} · {plan.reservation.contactName}</h3><p>{plan.reservation.departure.tour.name} · {plan.installmentCount} taksit · kalan {money(plan.remaining,plan.currency)}</p></div><span className="badge">{money(plan.paid,plan.currency)} ödendi</span></article>)}</div></section>
  </main>;
}
